version: '3.7'
services:
  db: # 서비스 명
    image: mysql:5.7 # 사용할 이미지
    restart: always
    container_name: mysql-demo # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - MYSQL_DATABASE=security
      - MYSQL_ROOT_PASSWORD=1234  # MYSQL 패스워드 설정 옵션
      - MYSQL_USER=cos
      - MYSQL_PASSWORD=cos1234
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/docker/mysql/init.sql:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbiitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
#networks:
#  rabbitmq_go_net:
#    driver: bridge

